### ISSUE TITLE
環境変数の値がnilになる

### ISSUE THREAD

**Issue by yogi1116** [yogi1116/crazy_man#61]
Natural Lnaguage APIを導入し、ローカルにてアプリの新規投稿を実行したところ下記のエラーが発生します。
```
undefined method `unpack1' for nil:NilClass
```
これは環境変数である`GOOGLE_CREDENTIALS`の値がnilであることを表しています。
このnilを解決したいです。

これまでの経緯は下記の通りです。
Natural Language APIを導入し機能確認が完了したところで開発を終了し、herokuにてデプロイを成功させました。
本番環境のアプリを開くと、投稿するタイミングでエラーが発生します(APIを呼び出すタイミング)。

投稿内容に不適切なカテゴリーなどが含まれていないかAPIに調べてもらい、含まれていれば投稿を
拒否する仕組みになっています。投稿するタイミングでエラーが発生するのでAPIの設定に問題があると判断しました。

下記はAPIを呼び出してるコードの一部になります。apiキーではなくOAuth2.0を使用しjsonキーでアプリを呼び出してます。
`'app/services/service_account.json'`がサービスアカウントのjsonキーです。
```
  def initialize(post)
    @post = post
    @credentials = Google::Auth::ServiceAccountCredentials.make_creds(
      json_key_io: File.open('app/services/service_account.json'),
      scope: SCOPE
    )
  end
```

エラーの原因として、
サービスアカウントのjsonキー`app/services/service_account.json`を公開しないよう.gitignoreしていたことが原因で、
heroku上で読み込めずエラーが発生していることが分かりました。

そのためjsonキーの内容を環境変数に格納することで、herokuの本番環境でもjsonキーが認識されAPIを呼び出せるよう
実装することにしました。
ターミナルにて下記のコマンドを実行し、環境変数を定義しました。
```
heroku config:set GOOGLE_CREDENTIALS=jsonキーの内容(全体をBase64エンコードした文字列)
```
APIを呼び出すコードを下記のように変更しました
```
  def initialize(post)
    @post = post
    @credentials = Google::Auth::ServiceAccountCredentials.make_creds(
      json_key_io: StringIO.new(Base64.decode64(ENV['GOOGLE_CREDENTIALS'])),
      scope: SCOPE
    )
  end
```

上記で解決すると思われたのですが、ローカルでAPIの機能確認を実施したところ
`undefined method 'unpack1' for nil:NilClass`エラーが発生してしまいました。

環境変数の定義に問題がないか`heroku config`コマンドで設定された変数の値を確認したのですが、間違いはありませんでした。

環境変数の値がnilになる原因が分かりません。
ご教授お願いします。

**Comment by Tsuchiya2** [comment]
json_key_ioに渡す値の長さや大きさが分からないので推測も含めていますが。
以下の方法とか試してみるといかがでしょうか。

- credentialsを使って値をcredentials.yml.encファイルに値を保存
- credentials.yml.encの読み取りを使って、json_key_ioに値を渡す
- 本番環境(Heroku)にmaster.keyを登録する

参考：https://qiita.com/NaokiIshimura/items/2a179f2ab910992c4d39

**Comment by yogi1116** [comment]
ご回答ありがとうございます！
つちや講師の有益な情報により、エラーを無事解決することができました。

以下はその手順を記載してます。


下記のコマンドで`credentials.yml.enc`を編集
```
$ EDITOR="vi" bin/rails credentials:edit
```

`credentials.yml.enc`にjsonファイル(サービスアカウント)を貼り付け。
インデントにとてもシビア。サーバー起動時のエラー原因の元となる。
```
google:
  natural_language_credentials: |
    {
      "type": "service_account",
      "project_id": "＊＊＊",
      "private_key_id": "＊＊＊＊＊",
      "private_key": "＊＊＊＊,
      // その他のキーと値
    }
secret_key_base: ＊＊＊
```

APIの呼び出し部分を編集。
```
def initialize(post)
    @post = post
    @credentials = Google::Auth::ServiceAccountCredentials.make_creds(
      json_key_io: StringIO.new(Rails.application.credentials.google[:natural_language_credentials]),
      scope: SCOPE
    )
```
最後にherokuにmaster.keyを登録。
キーの名前を`RAILS_MASTER_KEY`ではなく違う名前にすると本番環境でエラーが発生する。
```
heroku config:set RAILS_MASTER_KEY=master.keyの値
```

上記の手順で無事解決できました。ありがとうございました
