### ISSUE TITLE
MVPリリースレビュー

### ISSUE THREAD

**Issue by tmtkzk0823** [yogi1116/crazy_man#90]
@yogi1116 
お疲れ様です！

こちらMVPリリースレビューになります！

### 技術
concernやhelper、gemのfaradayなどを使ってコードが綺麗にかけている印象でした。
以下、細かい点ですがFBになります。
- NaturalLanguage APIを使って、禁止用語を設定しているかと思います。「死」や「害」などの言葉は判別できていそうですが、「殺」などの言葉はコメント等で投稿できてしまったので、禁止用語のレバートリーが増えるといいなと思いました。（現在、その投稿は削除済みです）
- ユーザビリティにも関係してきますが、「COMPLETE」「GIVE UP」各々の投稿で**ソートする機能**があると、投稿が増えた時もみやすくなるのではないかと思いました。

### ユーザビリティ
世界観が素敵でユーザーがアプリを使用する際、迷いづらい導線になっているかと思います！
以下細かい点ですが、FBになります。

- 投稿の「content」カラムの文章量でコメント数やいいね数の位置がずれてしまうようですので、投稿の下部に固定で表示してあげられると良さそうです。
- 「Read more」をクリックすると投稿の詳細ページに遷移するかと思うのですが、少々導線がわかりにくいような印象を受けたので、「**投稿自体をリンクにする」「Read moreのリンクをもう少し強調させる」**等を検討してもいいと思いました。
- 
以上です！

世界観をしっかり出して、ユーザーの印象に残るアプリケーションだと思いました！
LGTMです！

上記の内容を本リリース実装するタスクに組み込み、スケジュールを立ててみてください。

スケジュール決まりましたら共有をお願いできればと思います。

また上記レビューに関して、質問などありましたらスレッドに記載いただいてご連絡ください！

**Comment by yogi1116** [comment]
お疲れ様です
レビューありがとうございます！

質問があります。
挑戦内容にのみNatural Language APIを導入し不適切な内容の投稿を防止していましたが、
コメントへの導入は検討していませんでした。コメントにもNatural Language APIを導入した方がいいのでしょうか？

また投稿を編集する際は、Natural Lanugage APIを導入していませんが、導入するべきでしょうか？
理由としては、google cloudの「承認済みのリダイレクト URI」にAPIを呼び出すタイミング(URL)を記述するのですが、
create時はどのユーザーでもURLが同じなのに対し、update時はpost_idがurlに組み込まるため動的となり
「承認済みのリダイレクト URI」への記載方が分からなかったためです。
新規投稿時にAPIを導入するなら投稿編集時もAPIを導入しないのは不自然でしょうか？


投稿一覧にて「COMPLETE」「GIVE UP」を分けて表示できるようソート機能の導入と
コメント数やいいね数の位置ずれ、投稿一覧のRead more部分の分かり辛さは修正します。
ご指摘ありがとうございました！

**Comment by tmtkzk0823** [comment]
> 挑戦内容にのみNatural Language APIを導入し不適切な内容の投稿を防止していましたが、
コメントへの導入は検討していませんでした。コメントにもNatural Language APIを導入した方がいいのでしょうか？

上記承知しました！
私の勘違いでコメントの部分では無く、「**印象に残ったできごと」**の項目では「殺」などの言葉を投稿できてしまったのでご確認ください。
（混乱させてしまい申し訳ありません🙇）

> また投稿を編集する際は、Natural Lanugage APIを導入していませんが、導入するべきでしょうか？
理由としては、google cloudの「承認済みのリダイレクト URI」にAPIを呼び出すタイミング(URL)を記述するのですが、
create時はどのユーザーでもURLが同じなのに対し、update時はpost_idがurlに組み込まるため動的となり
「承認済みのリダイレクト URI」への記載方が分からなかったためです。
新規投稿時にAPIを導入するなら投稿編集時もAPIを導入しないのは不自然でしょうか？

新規投稿で`Natural Lanugage API`が導入されているのであれば、編集も導入してしてあるのが自然かなと思います。
(投稿してから編集で不適切な投稿がされる懸念が消えそうかつ、アプリの機能としての統一もできるかなと🙇‍♂️)
